"""Generate a Webots R2025a PROTO from the locked vendor M20 URDF."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

from m20_pro_mujoco_bridge.model import URDF_RELATIVE_PATH, resolve_model_dir


HERE = Path(__file__).resolve().parent
DEFAULT_OUTPUT = HERE / "scenes" / "generated" / "DeepRoboticsM20.proto"

# The vendor URDF assigns the exact same neutral-grey RGBA material to every
# mesh.  These presentation-only materials make the generated scene legible
# and follow the white/silver body, graphite joints and black wheels shown by
# DeepRobotics' official product photography. They never affect the locked
# mesh, collision shapes, inertia, joint limits, or controller.
PRESENTATION_MATERIALS = {
    "base_link": ("0.84 0.85 0.87", "0.36", "0.18"),
    "hipx": ("0.12 0.15 0.18", "0.43", "0.25"),
    "hipy": ("0.80 0.82 0.85", "0.42", "0.16"),
    "knee": ("0.14 0.18 0.22", "0.48", "0.20"),
    "wheel": ("0.025 0.030 0.035", "0.72", "0.0"),
}


def _presentation_material_for(link_name: str) -> tuple[str, str, str]:
    if link_name == "base_link":
        return PRESENTATION_MATERIALS["base_link"]
    for suffix in ("hipx", "hipy", "knee", "wheel"):
        if link_name.endswith(suffix):
            return PRESENTATION_MATERIALS[suffix]
    raise RuntimeError(f"Unexpected visual link in generated M20 PROTO: {link_name}")


def apply_presentation_materials(proto: str) -> str:
    """Replace only the URDF's uniform neutral-grey visual materials."""

    pattern = re.compile(
        r"(appearance DEF (?P<link>[A-Za-z0-9_]+)_material PBRAppearance \{\s*"
        r"baseColor )(?P<color>[0-9. ]+)(\s+roughness )(?P<roughness>[0-9.]+)"
        r"(\s+metalness )(?P<metalness>[0-9.]+)",
        flags=re.MULTILINE,
    )

    def replace(match: re.Match[str]) -> str:
        color, roughness, metalness = _presentation_material_for(match.group("link"))
        return (
            f"{match.group(1)}{color}{match.group(4)}{roughness}"
            f"{match.group(6)}{metalness}"
        )

    converted, count = pattern.subn(replace, proto)
    if count != 17:
        raise RuntimeError(f"Expected 17 M20 visual materials, found {count}")
    return converted


def generate(output: Path = DEFAULT_OUTPUT, model_dir: str | Path | None = None) -> Path:
    """Convert vendor URDF without changing geometry or joint limits.

    `urdf2webots` emits Windows path separators when invoked on Windows. Webots
    PROTO URLs are slash-delimited, so normalizing only those generated paths
    is mandatory and independently tested. Disabling mesh shadows avoids a
    renderer-only warning for the vendor base mesh; collision and geometry are
    untouched.
    """

    source = resolve_model_dir(model_dir) / URDF_RELATIVE_PATH
    output = output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            sys.executable,
            "-m",
            "urdf2webots.importer",
            "--input",
            str(source),
            "--output",
            str(output),
            "--box-collision",
            "--link-to-def",
            "--joint-to-def",
            "--target",
            "R2025a",
        ],
        check=True,
    )
    generated = output.read_text(encoding="utf-8")
    generated = generated.replace("\\", "/")
    generated = generated.replace("Shape {", "Shape {\n        castShadows FALSE")
    generated = apply_presentation_materials(generated)
    provenance = (
        "# Generated by generate_webots_proto.py from the vendor-published M20 URDF.\n"
        "# Source model license: BSD-3-Clause, DeepRoboticsLab/deep_robotics_model.\n"
        "# This converted Webots PROTO is not a vendor-supplied Webots model.\n"
    )
    header, separator, body = generated.partition("\n")
    if not header.startswith("#VRML_SIM") or not separator:
        raise RuntimeError("urdf2webots did not generate a valid R2025a PROTO header")
    output.write_text(header + "\n" + provenance + body, encoding="utf-8")
    if "\\" in output.read_text(encoding="utf-8"):
        raise RuntimeError("Generated Webots PROTO contains an invalid Windows path separator")
    return output


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    print(generate(args.output))
