"""Generate a Webots R2025a PROTO from the locked vendor X30 URDF."""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

from x30_pro_mujoco_bridge.model import URDF_RELATIVE_PATH, resolve_model_dir


HERE = Path(__file__).resolve().parent
DEFAULT_OUTPUT = HERE / "scenes" / "generated" / "DeepRoboticsX30.proto"

def apply_presentation_materials(proto: str) -> str:
    """Apply only renderer-safe URL normalization to the vendor visual output.

    The X30 URDF converter emits inline materials rather than named material
    definitions.  Retaining those exact source materials is safer than trying
    to infer a cosmetic mapping from link names, and keeps the generated
    visual model strictly source-derived.
    """

    return proto.replace("\\", "/")


def generate(output: Path = DEFAULT_OUTPUT, model_dir: str | Path | None = None) -> Path:
    """Convert vendor URDF without changing geometry or joint limits.

    `urdf2webots` emits Windows path separators when invoked on Windows. Webots
    PROTO URLs are slash-delimited, so normalizing only those generated paths
    is mandatory and independently tested. The source mesh, collision geometry,
    inertia, and joint limits remain untouched.
    """

    source = resolve_model_dir(model_dir) / URDF_RELATIVE_PATH
    output = output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            sys.executable,
            "-m",
            "urdf2webots.importer",
            "--input",
            str(source),
            "--output",
            str(output),
            "--box-collision",
            "--link-to-def",
            "--joint-to-def",
            "--target",
            "R2025a",
        ],
        check=True,
    )
    generated = output.read_text(encoding="utf-8")
    generated = apply_presentation_materials(generated)
    provenance = (
        "# Generated by generate_webots_proto.py from the vendor-published X30 URDF.\n"
        "# Source model license: BSD-3-Clause, DeepRoboticsLab/deep_robotics_model.\n"
        "# This converted Webots PROTO is not a vendor-supplied Webots model.\n"
    )
    header, separator, body = generated.partition("\n")
    if not header.startswith("#VRML_SIM") or not separator:
        raise RuntimeError("urdf2webots did not generate a valid R2025a PROTO header")
    output.write_text(header + "\n" + provenance + body, encoding="utf-8")
    if "\\" in output.read_text(encoding="utf-8"):
        raise RuntimeError("Generated Webots PROTO contains an invalid Windows path separator")
    return output


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    print(generate(args.output))
