"""Webots extern controller: the SAME policy and gait stack as MuJoCo.

Imports TrotController and NavPolicy unchanged from work/simulation/go2 and
adapts only the simulator I/O: Webots supervisor pose/velocity in, motor
torques out. Metrics mirror go2_nav.run_episode for the sim-to-sim report.

Launched by run_webots.py with WEBOTS_CONTROLLER_URL pointing at a world
generated by make_world.py. Env: TASK_FILE (task JSON), RESULT_FILE.
"""

import json
import math
import os
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).parents[2] / "go2"))
from controller import Supervisor            # noqa: E402  (Webots API)
from go2_gait import TrotController          # noqa: E402
from go2_nav import NavPolicy, GOAL_RADIUS   # noqa: E402

SETTLE_TIME = 1.0    # s of stand before the clock starts (Webots spawns
                     # the robot in the URDF rest pose, MuJoCo in "home")
MAX_TIME = 90.0
LEGS = ["FL", "FR", "RL", "RR"]
JOINTS = ["hip", "thigh", "calf"]


def quat_from_r(r):
    """Row-major 3x3 -> (w, x, y, z)."""
    w = math.sqrt(max(0.0, 1 + r[0] + r[4] + r[8])) / 2
    if w > 1e-6:
        return (w, (r[7] - r[5]) / (4 * w), (r[2] - r[6]) / (4 * w),
                (r[3] - r[1]) / (4 * w))
    return (0.0, 1.0, 0.0, 0.0)   # not reachable for an upright-ish trunk


def main():
    task = json.loads(pathlib.Path(os.environ["TASK_FILE"]).read_text())
    result_file = pathlib.Path(os.environ["RESULT_FILE"])
    obstacles = [tuple(ob) for ob in task["obstacles"]]
    goal = np.array(task["goal"])

    robot = Supervisor()
    dt_ms = int(robot.getBasicTimeStep())
    dt = dt_ms / 1000.0

    motors, sensors = [], []
    for leg in LEGS:
        for joint in JOINTS:
            m = robot.getDevice(f"{leg}_{joint}_joint")
            s = robot.getDevice(f"{leg}_{joint}_joint_sensor")
            s.enable(dt_ms)
            motors.append(m)
            sensors.append(s)

    node = robot.getSelf()
    obstacle_nodes = [robot.getFromDef(f"OBSTACLE_{i}")
                      for i in range(len(obstacles))]

    ctrl = TrotController(dt)
    policy = NavPolicy(goal, obstacles)

    q_prev = None
    start_xy = None
    prev_xy = None
    path_len = 0.0
    collisions = 0
    was_touching = [False] * len(obstacles)
    trajectory = []
    fell = False
    done = False
    step = 0
    sim_t = 0.0

    while robot.step(dt_ms) != -1:
        pos = np.array(node.getPosition())
        quat = quat_from_r(node.getOrientation())
        vel = node.getVelocity()   # world [vx, vy, vz, wx, wy, wz]
        q = np.array([s.getValue() for s in sensors])
        dq = np.zeros(12) if q_prev is None else (q - q_prev) / dt
        q_prev = q

        qpos = np.concatenate([pos, quat, q])
        qvel = np.concatenate([vel[:3], vel[3:6], dq])

        settling = robot.getTime() < SETTLE_TIME
        if settling:
            ctrl.set_command(0, 0, 0)
        elif step % 10 == 0:
            w, x, y, z = quat
            yaw = math.atan2(2 * (w * z + x * y), 1 - 2 * (y * y + z * z))
            cmd, done = policy.command(pos[0], pos[1], yaw)
            ctrl.set_command(*cmd)
        step += 1

        tau = ctrl.compute(qpos, qvel)
        for m, t in zip(motors, tau, strict=True):
            m.setTorque(float(t))

        if settling:
            continue
        if start_xy is None:
            start_xy = pos[:2].copy()
            prev_xy = start_xy
        sim_t += dt

        path_len += float(np.linalg.norm(pos[:2] - prev_xy))
        prev_xy = pos[:2].copy()
        if step % 50 == 0:
            trajectory.append([round(float(pos[0]), 3), round(float(pos[1]), 3)])

        for i, ob_node in enumerate(obstacle_nodes):
            touching = len(ob_node.getContactPoints()) > 0
            if touching and not was_touching[i]:
                collisions += 1
            was_touching[i] = touching

        w, x, y, z = quat
        roll = math.atan2(2 * (w * x + y * z), 1 - 2 * (x * x + y * y))
        pitch = math.asin(max(-1.0, min(1.0, 2 * (w * y - z * x))))
        if pos[2] < 0.15 or max(abs(roll), abs(pitch)) > 0.6:
            fell = True
            break
        if done or sim_t >= MAX_TIME:
            break

    final_dist = float(np.linalg.norm(goal - prev_xy))
    start_dist = float(np.linalg.norm(goal - start_xy))
    result = {
        "goal": list(goal),
        "time_s": round(sim_t, 2),
        "final_goal_distance_m": round(final_dist, 3),
        "path_completion": round(max(0.0, 1 - final_dist / start_dist), 3),
        "path_length_m": round(path_len, 2),
        "collisions": collisions,
        "fell": fell,
        "reached": bool(final_dist < GOAL_RADIUS and not fell),
        "trajectory": trajectory,
    }
    result_file.write_text(json.dumps(result, indent=1))
    summary = {k: v for k, v in result.items() if k != "trajectory"}
    print(f"webots episode done: {json.dumps(summary)}", flush=True)
    robot.simulationQuit(0)


if __name__ == "__main__":
    main()
