"""Generate go2_simple_kin.urdf from the menagerie go2.xml.

PyBullet's loadMJCF cannot parse the menagerie Go2 MJCF (it uses MuJoCo 3.x
features: class/default inheritance, freejoint, actuators, mesh visuals), so
like the Spot branch we commit a mesh-free kinematic URDF. Unlike Spot, this
URDF is *generated from the committed go2.xml itself* (joint frames, axes,
limits and link offsets are read straight from the MJCF), which keeps the two
simulators' kinematics identical by construction.

Regenerate with:

    python make_go2_kin_urdf.py models/mujoco_menagerie/unitree_go2/go2.xml

Joint axes and limits come from the MJCF default classes:
  abduction  axis 1 0 0  range [-1.0472,  1.0472]
  front_hip  axis 0 1 0  range [-1.5708,  3.4907]
  back_hip   axis 0 1 0  range [-0.5236,  4.5379]
  knee       axis 0 1 0  range [-2.7227, -0.83776]
"""

import pathlib
import re
import sys

CLASS_AXIS = {
    "abduction": "1 0 0",
    "front_hip": "0 1 0",
    "back_hip": "0 1 0",
    "knee": "0 1 0",
}
CLASS_RANGE = {
    "abduction": (-1.0472, 1.0472),
    "front_hip": (-1.5708, 3.4907),
    "back_hip": (-0.5236, 4.5379),
    "knee": (-2.7227, -0.83776),
}


def main():
    here = pathlib.Path(__file__).parent
    if len(sys.argv) > 1:
        xml_path = pathlib.Path(sys.argv[1])
    else:
        xml_path = here.parent / "models" / "mujoco_menagerie" \
            / "unitree_go2" / "go2.xml"
    xml = xml_path.read_text(encoding="utf-8")

    # Tokenize body/joint open+close tags; nested `body` elements use a
    # stack so every joint is attributed to its direct parent body. The
    # <default> class blocks also contain joint tags without names; those are
    # skipped entirely.
    tokens = re.findall(
        r"<(/?)(body|joint|default)\b([^>]*?)(/?)>", xml)
    stack = []
    chain = []   # (joint_name, class, parent_link, child_link, origin_xyz)
    in_default = 0
    for closing, kind, attrs, selfclose in tokens:
        if kind == "default":
            in_default += 1 if not closing else -1
            continue
        if in_default > 0:
            continue
        if kind == "body":
            if closing:
                stack.pop()
                continue
            if selfclose:
                continue
            m = re.search(r'name="([^"]+)"', attrs)
            name = m.group(1) if m else f"body{len(stack)}"
            stack.append(name)
        else:  # joint
            if closing:
                continue
            jm = re.search(r'name="([^"]+)"', attrs)
            cm = re.search(r'class="([^"]+)"', attrs)
            jname = jm.group(1) if jm else "joint"
            jclass = cm.group(1) if cm else "knee"
            parent = stack[-2] if len(stack) >= 2 else "base_link"
            child = stack[-1]
            # The child link's origin is this joint's offset; the joint tag
            # itself carries no origin, so we resolve it after the closing
            # body tag by pairing joints to their child body position.
            chain.append({"jname": jname, "jclass": jclass,
                          "parent": parent, "child": child, "pos": None})

    # Resolve link origins: each child link's origin equals the position of
    # the body that carries the joint (the joint is at the child body's
    # frame origin, exactly as in the MJCF where the joint is declared on
    # the body).
    body_pos = dict(re.findall(
        r'<body name="([^"]+)"\s+pos="([^"]+)"', xml))
    for entry in chain:
        entry["pos"] = body_pos.get(entry["child"], "0 0 0")

    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        '<!-- Generated by make_go2_kin_urdf.py from go2.xml. Kinematics only;',
        '     joint frames, axes and limits are read directly from the MJCF.',
        '     Do not hand-edit. -->',
        '<robot name="go2_simple_kin">',
        '  <link name="base_link"/>',
    ]
    for entry in chain:
        xyz = " ".join(entry["pos"].split())
        lo, hi = CLASS_RANGE[entry["jclass"]]
        lines += [
            f'  <link name="{entry["child"]}"/>',
            f'  <joint name="{entry["jname"]}" type="revolute">',
            f'    <parent link="{entry["parent"]}"/>',
            f'    <child link="{entry["child"]}"/>',
            f'    <origin xyz="{xyz}"/>',
            f'    <axis xyz="{CLASS_AXIS[entry["jclass"]]}"/>',
            f'    <limit lower="{lo}" upper="{hi}" effort="1000" velocity="20"/>',
            f'  </joint>',
        ]
    lines.append("</robot>")

    out = here / "go2_simple_kin.urdf"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out} ({len(chain)} joints: "
          + ", ".join(f"{e['jname']}[{e['jclass']}]" for e in chain) + ")")


if __name__ == "__main__":
    main()
